name: Build on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on tags starting with 'v', e.g., 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Locate MSBuild
        id: locate-msbuild
        run: |
          echo "##[set-output name=vs-path;]$(vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath)"
          echo "MSBuild located at ${{ steps.locate-msbuild.outputs.vs-path }}"

      - name: Build the solution
        run: ${{ steps.locate-msbuild.outputs.vs-path }}\MSBuild\Current\Bin\MSBuild.exe /t:Build /p:Configuration=Release /p:Platform=x64 YourSolution.sln

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            **/*.exe
            **/*.dll
            **/*.pdb
            **/*.lib
            # Add any other files you want to keep
